version: 2

workflows:
    version: 2
    commit:
        jobs:
            - build:
                context: docker-hub-transpiria
                filters:
                    branches:
                        only: master

jobs:
    build:
        docker:
            - image: circleci/node
        working_directory: ~/app
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true
            - restore_cache:
                keys:
                    - dependencies-{{ checksum "package-lock.json" }}
                    - dependencies-
            - run:
                name: Restore packages
                command: npm install
            - save_cache:
                paths:
                    - node_modules
                key: dependencies-{{ checksum "package-lock.json" }}
            - run:
                name: Build & Push Images
                command: |
                    docker login --username "$DTR_USERNAME" --password $DTR_PASSWORD docker.io
                    npx scri
